import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 dark:bg-zinc-900`}
      >
        <div className="grid grid-cols-[280px_1fr] grid-rows-[60px_1fr] h-screen">
          <Sidebar />
          <Navbar />
          <main className="col-start-2 row-start-2 overflow-auto bg-gray-50 dark:bg-zinc-800">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
